export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const UPDATE_MODULE = 'UPDATE_MODULE';
export const CREATE_MODULE = 'CREATE_MODULE';
export const DELETE_MODULE = 'DELETE_MODULE';
export const CHECK_MODULE = 'CHECK_MODULE';
export const GOBEHIND = 'GOBEHIND';

export const LIMITSCOPE = 'LIMITSCOPE';
export const SHOWRULER = 'SHOWRULER';
export const SHOWSTATUSBAR = 'SHOWSTATUSBAR';
export const WORKPANELWIDTH = 'WORKPANELWIDTH';
export const WORKPANELHEIGHT = 'WORKPANELHEIGHT';
export const RESET_WORKPANEL = 'RESET_WORKPANEL';

export const CREATE_CANVAS = 'CREATE_CANVAS';
export const UPDATE_CANVAS = 'UPDATE_CANVAS';
export const DELETE_CANVAS = 'DELETE_CANVAS';
export const CHECK_CANVAS = 'CHECK_CANVAS';
export const RESET_CANVAS = 'RESET_CANVAS';

export const SWITCH_PANEL = 'SWITCH_PANEL';
export const RESET_EDITPANEL = 'RESET_EDITPANEL';
